define rek = Character("[name]", color="#1890FF")
define cyp = Character('cypeppypep', color='#E52B50')
define anc = Character('Анкета', color='#CD9575', what_color='#1E1112', kind=nvl)
define anon_ant = Character('?', color='#AF2B1E')
define pod = Character('Подводный', color='#531A50')
define anon_pod = Character('?', kind=pod)
define rekMind = Character(what_prefix="«", what_suffix="»", kind=rek)
define naidjel = Character('Найджел', color='#4c3baa')
define anon_naidjel = Character('?', kind=naidjel)